### ISSUE TITLE
Are there any examples for the using in surgery?

### ISSUE THREAD

**Issue by LiZhenzhuBlog** [UCL/scikit-surgeryvtk#154]
Are there any examples for the using in surgery?

**Comment by thompson318** [comment]
Hello, are you looking for code examples or application examples?
scikit-surgeryvtk is used in the SmartLiver system currently undergoing trials in surgery, there's a publication here, 
https://link.springer.com/article/10.1007/s00464-020-07807-x figure 1 shows an overlay image. I don't think the code is publicly available though.
scikit-surgeryvtk is also used in scikit-surgerydavinci which you should be able to access here;
https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/scikit-surgerydavinci
scikit-surgerybard (Basic augmented reality demonstration) https://github.com/UCL/scikit-surgerybard isn't used in surgery, but does give a good demo of how to set up an AR system for surgery, that could be used as a start, if you use scikit-surgerynditracker instead of the ArUco trackers.

**Comment by LiZhenzhuBlog** [comment]
Thanks.
